version: "3.8"
services:
  eyetracking_vs:
    container_name: eyetracking_vs
    working_dir: /home/user/eyetracking_vs
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    network_mode: host # NOTE: for some reason this is sometimes forwarding a ton of ports on Odin crashing it, probably need a more selective setting.
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../Eyetracker-Visual-Servoing:/home/user/eyetracking_vs
      - /tmp/.X11-unix:/tmp/.X11-unix
